[workspace]

members = [
    "crates/uiautomation_derive",
    "crates/uiautomation",
    "samples/*",
    "tests/*",
]

resolver = "2"

[workspace.dependencies]

windows = "0.62.0"
windows-core = "0.62.0"
