[package]
name = "uia_async_event"
version = "0.1.0"
edition = "2024"

[dependencies]

uiautomation = { path = "../../crates/uiautomation", features = ["process", "event"]}
windows = { workspace = true, features = []}
